#!/usr/bin/env python
# -*- coding: utf-8 -*-

import random

quotes = [
      'You must do what you feel is right, of course.',
      'Mos Eisley Spaceport. You will never find a more wretched hive of scum and villainy. We must be cautious.',
      'Your eyes can deceive you. Don’t trust them.',
      'Remember... the Force will be with you, always.',
      'In my experience, there is no such thing as luck.',
      'These aren\'t the droids you\'re looking for.',
      'I felt a great disturbance in the Force, as if millions of voices suddenly cried out in terror and were suddenly silenced.',
      'Use the Force, Luke.',
      'You can\'t win, Darth. If you strike me down, I shall become more powerful than you could possibly imagine.',
      'That\'s no moon. It\'s a space station.',
      'Luke! Don\'t give in to hate. That leads to the Dark Side.',
      'Who\'s the more foolish, the fool or the fool who follows him?',
      'And these blast points, too accurate for Sandpeople. Only Imperial Stormtroopers are so precise.',
      'I find your lack of faith disturbing.',
      'The circle is now complete. When I left you, I was but the learner. Now I am the master.',
      'The Force is with you, young Skywalker, but you are not a Jedi yet.',
      'No. I am your father.',
      'Impressive. Most impressive.',
      'I am altering the deal. Pray I don\'t alter it any further.',
      'You underestimate the power of the Dark Side. If you will not fight, then you will meet your destiny.',
      'You have failed me for the last time, Admiral!',
      'The Force is strong with this one.',
      'The ability to destroy a planet is insignificant next to the power of the Force.',
      'Do. Or do not. There is no try.',
      'You must unlearn what you have learned.',
      'When nine hundred years old you reach, look as good you will not.',
      'Truly wonderful, the mind of a child is.',
      'A Jedi uses the Force for knowledge and defense, never for attack.',
      'Adventure. Excitement. A Jedi craves not these things.',
      'Size matters not. Judge me by my size, do you? ',
      'Fear is the path to the dark side…fear leads to anger…anger leads to hate…hate leads to suffering.',
      'Wars not make one great.',
      'Luminous beings are we…not this crude matter.',
      'Difficult to see. Always in motion is the future.',
      'Control, control, you must learn control! ',
      'I\'ll never turn to the Dark Side. You\'ve failed, your highness. I am a Jedi, like my father before me.',
      'If there\'s a bright center to the universe, you\'re on the planet that it\'s farthest from.',
      'I\'m Luke Skywalker. I\'m here to rescue you.',
      'The Force is strong in my family. My father has it. I have it. My sister has it. You have that power, too.',
      'But I was going into Tosche Station to pick up some power converters!',
      'Chewie...we\'re home.',
      'Never tell me the odds.',
      'Women always figure out the truth. Always.',
      'Fast ship? You\'ve never heard of the Millennium Falcon? It\'s the ship that made the Kessel Run in less than twelve parsecs.',
      'Great shot, kid, that was one in a million!',
      'Boring conversation anyway. LUKE, WE\'RE GONNA HAVE COMPANY!',
      'No reward is worth this.',
      'Wonderful girl. Either I\'m going to kill her or I\'m beginning to like her.',
      'Look, Your Worshipfulness, let\'s get one thing straight. I take orders from just one person: me.',
      'Help me, Obi-Wan Kenobi. You\'re my only hope.',
      'Aren\'t you a little short for a stormtrooper.',
      'Someone has to save our skins. Into the garbage chute, fly boy.',
      'Will someone get this big walking carpet out of my way.',
      'You needn\'t worry about your reward. If money is all that you love, then that\'s what you\'ll receive.',
      'I suggest a new strategy, R2: let the Wookiee win.',
      'We seem to be made to suffer. It\'s our lot in life.',
      'Sir, the possibility of successfully navigating an asteroid field is approximately 3,720 to 1.',
      'Sir, it\'s quite possible this asteroid is not entirely stable.',
      'Don’t call me a mindless philosopher, you overweight glob of grease.',
      'Young fool... Only now, at the end, do you understand...',
      'Your feeble skills are no match for the power of the Dark Side.',
      'Now, you will pay the price for your lack of vision!',
      'I will make it legal.'
      'Many Bothans died to bring us this information.',
      'Charming to the last. You don\'t know how hard I found it, signing the order to terminate your life.',
      'It\'s a trap!',
      'So this is how liberty dies…with thunderous applause.',
      'He\'s no good to me dead.',
      'I\'ve got a bad feeling about this.',
      'May the force be with you.',
      'Penis.'
]

def getQuote():
      strQuote = random.choice(quotes)
      return strQuote